# render.yaml

services:
  - type: web
    plan: free
    name: threejs-niece-gift
    runtime: docker
    envVars:
      
      # Image-specific vars (richarvey/nginx-php-fpm)
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: 1
      - key: REAL_IP_HEADER
        value: 1
      - key: SKIP_COMPOSER
        value: 1
